name: Document Conversion

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install tools & font stack
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-latex-base \
            texlive-fonts-extra \
            pdftk \
            fonts-noto \
            fonts-noto-cjk \
            fonts-noto-core \
            fonts-noto-extra \
            fonts-noto-ui-core \
            fonts-dejavu \
            fonts-liberation

      - name: Convert documents and sign PDFs
        run: |
          mkdir -p outputs signed

          # 1. Generate signature overlay PDF
          pdflatex -output-directory=outputs assets/signature_overlay.tex

          for file in letters/*.md; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .md)

            TITLE=$(grep -m 1 '^title:' "$file" | cut -d'"' -f2 || echo "${base} Recommendation Letter")

            # PDF
            pandoc "$file" \
              -o "outputs/${base}.pdf" \
              --pdf-engine=xelatex \
              -V mainfont="Noto Serif" \
              -V sansfont="Noto Sans" \
              -V monofont="Noto Sans Mono" \
              -V lang="ru-RU" \
              --metadata title="$TITLE" \
              -V geometry:margin=2cm

            # Apply signature overlay
            pdftk "outputs/${base}.pdf" stamp "outputs/signature_overlay.pdf" output "signed/${base}-signed.pdf"

            # DOCX
            pandoc "$file" \
              -o "outputs/${base}.docx" \
              --metadata title="$TITLE"

            # HTML
            pandoc "$file" \
              -o "outputs/${base}.html" \
              --self-contained \
              --metadata title="$TITLE" \
              --metadata lang="ru" \
              --css=https://cdn.jsdelivr.net/npm/water.css@2/out/water.css

            # Plain text
            pandoc "$file" -o "outputs/${base}.txt" -t plain
          done

      - name: Upload converted documents
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: outputs/

      - name: Upload signed PDFs
        uses: actions/upload-artifact@v4
        with:
          name: signed-documents
          path: signed/
