name: Document Conversion

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-fonts-extra \
            wkhtmltopdf \
            libreoffice \
            unoconv \
            fonts-dejavu \
            fonts-noto

      - name: Convert documents
        run: |
          mkdir -p outputs
          for file in letters/*.md; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .md)
          
            # 1. PDF (Professional Print)
            pandoc "$file" \
              -o "outputs/${base}.pdf" \
              --pdf-engine=xelatex \
              -V mainfont="Noto Serif" \
              -V lang="ru-RU" \
              --template=eisvogel
          
            # 2. DOCX (Editable Word)
            pandoc "$file" -o "outputs/${base}.docx"
          
            # 3. ODT (OpenOffice/LibreOffice)
            pandoc "$file" -o "outputs/${base}.odt"
          
            # 4. HTML (Web Version)
            pandoc "$file" \
              -o "outputs/${base}.html" \
              --self-contained \
              --css=github-pandoc.css
          
            # 5. Plain Text (Fallback)
            pandoc "$file" -o "outputs/${base}.txt" -t plain
          done

      - name: Package EPUB (optional)
        if: ${{ always() }}
        run: |
          for file in letters/*.md; do
            base=$(basename "$file" .md)
            pandoc "$file" -o "outputs/${base}.epub" --toc
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: outputs/
          retention-days: 7