name: Convert Letters
on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Install Pandoc + tools
      - name: Setup environment
        run: |
          for i in {1..3}; do
            sudo apt-get update -y && \
            sudo apt-get install -y pandoc texlive-latex-base wkhtmltopdf && \
            break || sleep 15
          done

      # Convert all .md files to PDF/DOCX
      - name: Convert Markdown to outputs
        run: |
          # Create outputs dir (no error if exists)
          mkdir -p outputs/ || true
          
          # Install dependencies only if missing
          command -v pandoc >/dev/null || sudo apt-get install -y pandoc
          dpkg -l | grep texlive-xcolor >/dev/null || sudo apt-get install -y texlive-xcolor
          
          # Convert files
          for file in letters/*.md; do
            [ -f "$file" ] || continue  # Skip if no files
            base=$(basename "$file" .md)
            pandoc "$file" -o "outputs/${base}.pdf" --pdf-engine=pdflatex --fail-if-warnings
            pandoc "$file" -o "outputs/${base}.docx"
            pandoc "$file" -o "outputs/${base}.html"
          done

      # Optional: Embed digital signature (if field exists)
      - name: Sign PDFs
        if: ${{ contains(github.event.head_commit.message, 'sign') }}
        run: |
          for file in letters/*.md; do
            base=$(basename "$file" .md)
            signature=$(grep 'signature:' "$file" | cut -d' ' -f2)
            if [ -n "$signature" ]; then
              ./scripts/sign_pdf.sh "outputs/${base}.pdf" "$signature"
            fi
          done

      # Commit outputs back to repo
      - name: Upload outputs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/
          git commit -m "Auto-generated PDF/DOCX"
          git push