name: Document Conversion

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up LaTeX and Pandoc
        run: |
          # Add deadsnakes PPA for reliable packages
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:jonathonf/texlive
          sudo apt-get update

          # Install minimal required packages
          sudo apt-get install -y --no-install-recommends \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            lmodern \
            fonts-liberation

      - name: Convert documents
        run: |
          mkdir -p outputs
          for file in letters/*.md; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .md)
            
            # PDF with XeLaTeX for Unicode support
            pandoc "$file" \
              -o "outputs/${base}.pdf" \
              --pdf-engine=xelatex \
              -V mainfont="Liberation Serif" \
              -V lang=russian
            
            # DOCX conversion
            pandoc "$file" -o "outputs/${base}.docx"
          done

      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: converted-documents
          path: outputs/