name: Document Conversion

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pandoc \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-latex-extra \
            lmodern \
            fonts-liberation \
            fonts-noto

      - name: Convert documents
        run: |
          mkdir -p outputs
          for file in letters/*.md; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .md)
          
            # PDF with proper Russian language support
            pandoc "$file" \
              -o "outputs/${base}.pdf" \
              --pdf-engine=xelatex \
              -V mainfont="Noto Serif" \
              -V lang="ru-RU" \
              -V geometry:margin=2cm
            
            # DOCX conversion
            pandoc "$file" -o "outputs/${base}.docx"
          done

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: outputs/