name: Document Conversion

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-fonts-extra \
            fonts-dejavu \
            fonts-noto \
            wget

          # Install Eisvogel template
          mkdir -p ~/.pandoc/templates
          wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v2.5.0/eisvogel.tar.gz -O /tmp/eisvogel.tar.gz
          tar -xzf /tmp/eisvogel.tar.gz -C ~/.pandoc/templates/

      - name: Convert documents
        run: |
          mkdir -p outputs
          for file in letters/*.md; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .md)
            
            # Extract title from YAML or filename
            TITLE=$(grep -m 1 '^title:' "$file" | cut -d'"' -f2 || echo "Recommendation Letter - ${base}")
            
            # 1. PDF with Eisvogel template
            pandoc "$file" \
              -o "outputs/${base}.pdf" \
              --template=eisvogel \
              --pdf-engine=xelatex \
              -V mainfont="Noto Serif" \
              -V lang="ru-RU" \
              --metadata title="$TITLE"
            
            # 2. DOCX (with proper title)
            pandoc "$file" \
              -o "outputs/${base}.docx" \
              --metadata title="$TITLE"
            
            # 3. HTML (with title)
            pandoc "$file" \
              -o "outputs/${base}.html" \
              --self-contained \
              --metadata title="$TITLE" \
              --css=https://cdn.jsdelivr.net/npm/water.css@2/out/water.css
            
            # 4. Plain Text
            pandoc "$file" \
              -o "outputs/${base}.txt" \
              -t plain \
              --metadata title="$TITLE"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: outputs/