name: Document Conversion

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install complete font system
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-fonts-extra \
            fonts-noto \
            fonts-noto-mono \
            fonts-noto-extra \
            fonts-symbola \  # Special symbols coverage
            fonts-liberation \
            fonts-dejavu

      - name: Convert documents
        run: |
          mkdir -p outputs
          for file in letters/*.md; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .md)
            
            # 1. PDF with full symbol support
            pandoc "$file" \
              -o "outputs/${base}.pdf" \
              --pdf-engine=xelatex \
              -V mainfont="Noto Serif, Symbola" \  # Fallback to Symbola
              -V sansfont="Noto Sans, Symbola" \
              -V monofont="Noto Sans Mono" \
              -V mathfont="Noto Sans Math" \
              -V lang="ru-RU" \
              --metadata title="$(grep -m 1 '^title:' "$file" | cut -d'"' -f2 || echo "${base}")" \
              -V geometry:margin=2cm
            
            # 2. DOCX (fallback to ASCII minus if needed)
            sed 's/−/-/g' "$file" | pandoc -o "outputs/${base}.docx"
            
            # 3. HTML with symbol fallbacks
            pandoc "$file" \
              -o "outputs/${base}.html" \
              --self-contained \
              --metadata title="$(grep -m 1 '^title:' "$file" | cut -d'"' -f2 || echo "${base}")" \
              --css=https://cdn.jsdelivr.net/npm/water.css@2/out/water.css
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: outputs/