name: Document Conversion

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-latex-extra \
            lmodern \
            fonts-liberation \
            fonts-noto

      - name: Convert Documents
        run: |
          mkdir -p outputs
          for file in letters/*.md; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .md)
            
            # PDF with XeLaTeX
            pandoc "$file" \
              -o "outputs/${base}.pdf" \
              --pdf-engine=xelatex \
              -V mainfont="Liberation Serif" \
              -V lang=russian
            
            # DOCX conversion
            pandoc "$file" -o "outputs/${base}.docx"
          done

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: outputs/