name: Document Conversion

on: push

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install complete LaTeX system
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-extra \
            lmodern \
            fonts-liberation \
            fonts-noto \
            fonts-roboto \
            fonts-dejavu

      - name: Convert documents
        run: |
          mkdir -p outputs
          for file in letters/*.md; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .md)
            
            # PDF with XeLaTeX and proper font setup
            pandoc "$file" \
              -o "outputs/${base}.pdf" \
              --pdf-engine=xelatex \
              -V mainfont="DejaVu Serif" \
              -V sansfont="DejaVu Sans" \
              -V monofont="DejaVu Sans Mono" \
              -V lang="ru-RU" \
              -V geometry:margin=2cm
            
            # DOCX conversion
            pandoc "$file" -o "outputs/${base}.docx"
          done

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: converted-documents
          path: outputs/